### PR TITLE
Back end setup

### PR DESCRIPTION
**Pull request by WilcoxJ**
This sets up the C# back end. To run it you open the solution file (AttorneryScheduler.sln) from visual studio

To build and launch click the play button:
image

If you get a package error after attempting build you should install the following packages from Tools > NuGet Package Manager 

"Microsoft.Data.Sqlite.Core" Version="8.0.3"
"Microsoft.EntityFrameworkCore" Version="7.0.0" 
"Microsoft.EntityFrameworkCore.Sqlite.Core" Version="7.0.0" 
"SQLite" Version="3.13.0" 

Be sure to select the correct version
image

### CODE REVIEW

**Comment by WilcoxJ** [comment]
lmk if you have any questions :)

**Comment by tmwlcx** [comment]
I have a lot of questions. What IDE should I use to work with this? Visual Studio Community and if so is it free? Is there a C# plugin for VS code? Have you tried it and is it any good? Maybe you should do a walkthrough of this?

**Review by tmwlcx — APPROVED** [review]
Hold on to your butts

**Comment by WilcoxJ** [comment]
Yes I believe you can use VSCode but I would recommend Visual Studio Community as it has a better debugger, package manager and is much easier to identify build issues. We can walk through this together but once you install those 4 packages, you should be able to click the play button and see a browser window launch with this:
image

**Comment by tmwlcx** [comment]
:) getting there!

**Pull request merged**
